[package]
name = "ngram-tools"
version = "0.1.0"
authors = ["Duane Johnson <duane.johnson@gmail.com>"]
edition = "2018"

[dependencies]
gumdrop = "0.6"
# log = "0.4.7"
grep-cli = "0.1"
termcolor = "*"